intermediateCertificates.url = https://ccadb.my.salesforce-sites.com/mozilla/PublicAllIntermediateCertsWithPEMCSV
intermediateCertificates.outputFile = lists/intermediate.pem
intermediateCertificates.count.minimum = 1000
intermediateCertificates.count.maximum = 3000
