#!/usr/bin/env python3
#
# Converts a text file containing app modules to JSON
#
# The text file must be UTF-8 encoded.
#
# The text has the format:
#
# Name: app A
#
# Description:
# de: ...
# en: ...
#
# Domains:
# ...
# 
# Name: app B
# ...
#
import sys
import re
import json

if len(sys.argv) != 3:
    sys.exit(f'Usage: {sys.argv[0]} <text file> <start ID>')

infile = sys.argv[1]
app_id = int(sys.argv[2])

pattern = re.compile(r'Name: (.*)\n\nDescription:\nde: (.*)\nen: (.*)\n\nDomains:\n((.+\n)+)')
pattern_ip = re.compile('^[0-9./]+$')

# Split lines into domains and IPs:
def split_domains(str):
    domains = []
    ips = []
    for s in str.strip().split('\n'):
        s = s.strip()
        if pattern_ip.match(s):
            ips.append(s)
        else:
            domains.append(s)
    return domains, ips

def create_app(app_id, name, de, en, domains):
    if de == 'undefined': de = ''
    if en == 'undefined': en = ''

    domains, ips = split_domains(domains)

    name = name.strip()
    de = de.strip()
    en = en.strip()

    return {'name': name,
            'description': {'de': de, 'en': en},
            'whitelistedDomains': domains,
            'whitelistedIPs': ips,
            'id': app_id,
            'enabledPerDefault': False,
            'hidden': False
           }

apps = []
with open(infile, encoding='utf-8') as f:
    txt = f.read()
    for match in pattern.finditer(txt):
        apps.append(create_app(app_id, match.group(1), match.group(2), match.group(3), match.group(4)))
        app_id += 1

print(json.dumps(apps, ensure_ascii=False, indent=4))
